# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = waybar & hyprpaper
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = nm-applet --indicator
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
# exec-once = hyprpaper
exec-once = swww-daemon
# exec-once = swww img /home/alex/Pictures/Wallpapers/PC/Forest3.png
exec-once = swww img /home/alex/Pictures/Wallpapers/PC/Forest3.png --outputs DP-1
exec-once = swww img /home/alex/Pictures/Wallpapers/PC/Forest3.png --outputs eDP-1
# Apply catpuccin themes to gnome disks and thunar
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "catppuccin-mocha-mauve-standard+default"
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
